//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDONHANG
    {
        public string IDDonHang { get; set; }
        public string IDShipper { get; set; }
        public string Mota { get; set; }
        public string IDCTDONHANG { get; set; }
        public string PhiShip { get; set; }
        public string DONGIA { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SHIPPER SHIPPER { get; set; }
        public virtual PHI PHI { get; set; }
    }
}
